# Generated by Django 4.1 on 2022-12-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hwid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
