# Generated by Django 4.1 on 2022-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_profile_hwid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dll',
            field=models.FileField(blank=True, null=True, upload_to='dlls/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exe',
            field=models.FileField(blank=True, null=True, upload_to='exes/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
