# Generated by Django 4.1 on 2022-12-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_product_dll_alter_product_exe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exe',
        ),
        migrations.AddField(
            model_name='product',
            name='driver',
            field=models.FileField(blank=True, null=True, upload_to='driver/'),
        ),
    ]
